traj_chosen_topic: '/rhcontroller/traj_chosen'

debug:
    ip_topic: '/sim_car_pose/pose'
    flag:
        viz_rollouts: true
        current_path: true
        viz_traj_chosen: true
        viz_cost_fn: true
    viz_rollouts:
        n: 4
        print_stats: false
    traj_chosen_trace:
        rate: 1
